### ISSUE TITLE
Codex Deck Scrolling Bug

### ISSUE THREAD

**Issue by NukeDragon** [Shockah/Nickel#86]
https://github.com/Shockah/Nickel/assets/39510311/1c0329f2-e8ce-4281-93a6-2e0fc1528a0d

For some reason, I cannot scroll down on the deck view more than a tiny bit. Removing any decks prevents scrolling at all. At the time I had 32 decks installed.

**Comment by Shockah** [comment]
A user reported they had issue scrolling with exactly 8 modded decks.

**Comment by Shockah** [comment]
Fixed in upcoming Nickel 1.0.0.
