### ISSUE TITLE
Logbook replacement shows invalid run info

### ISSUE THREAD

**Issue by Shockah** [Shockah/Nickel#96]

**Comment by bdr99** [comment]
By the way, why was the logbook replaced? I preferred the layout of the old logbook.

**Comment by Shockah** [comment]
@bdr99 the original logbook cannot fit modded runs as soon as you have like 2 modded characters installed.

**Comment by bdr99** [comment]
@Shockah That makes sense, thanks for explaining! I don't have any modded characters installed, so the original logbook worked fine for me. Would it be possible for the logbook replacement to only be enabled when modded characters are installed? That way we can have the best of both worlds.

**Comment by Shockah** [comment]
@bdr99 sure, should be pretty easy. I'll do that when I get to fixing this bug.

**Comment by bdr99** [comment]
@Shockah Awesome, thanks!
