### ISSUE TITLE
Harmony log file spitting out externally

### ISSUE THREAD

**Issue by ZadratAntares** [Shockah/Nickel#99]
On running Nickel harmony.log.txt is created on the desktop (windows 11, up to date). highly irritating for organised desktops

**Comment by Shockah** [comment]
That would be an issue with one of the mods, not Nickel itself, but it would be hard to tell which one.

**Comment by Shockah** [comment]
I've pinpointed it to the Eddie mod at the very least and notified the author. It could be more mods too.

**Comment by ZadratAntares** [comment]
ah, wow! thank you so much - I should probably have mentioned a modlist :')
